wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701814281.561048
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.12.0
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
